feed/urls.py
from django.urls import path

from . import views

app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new-post/", views.PostCreateView.as_view(), name="new_post"),
]

profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path("<str:username>/", views.ProfileDetailView.as_view(), name="detail"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
]

til/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from feed import urls as feed_urls
from django.conf import settings
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

feed/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Post(models.Model):

    text = models.CharField(max_length=240, null=False, blank=False)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    
    def __str__(self):
        return self.text[0:100]

followers/models.py
from django.contrib.auth.models import User
from django.db import models

class Follower(models.Model):
    followed_by= models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="followed_by"
    )
    following=models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following"
    )


    def __str__(self):
        return f"{self.followed_by.id} is following {self.following.id}"

    class Meta:
        unique_together=('followed_by', 'following',)


profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = ImageField(upload_to='profiles')

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

feed/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post
from django.shortcuts import render


class HomePage(ListView):
    http_method_names= ["get"]
    model = Post
    template_name = "feed/homepage.html"
    context_object_name = "posts"
    queryset = Post.objects.all().order_by('-id')[0:12]


class PostDetailView(DetailView):
    http_method_names= ["get"]
    model = Post
    template_name = "feed/detail.html"
    context_object_name = "post"


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "feed/new-post.html"
    fields = ['text']
    success_url = "/"

    
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        obj=form.save(commit=False)
        obj.author=self.request.user
        obj.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):

        post = Post.objects.create(
            text=request.POST.get("text"),
            author=request.user,
        )
        return render(
            request,
            "includes/post.html",
            {
                "post": post,
                "show_detail_link": True,
            },
            content_type="application/html"
        )

followers/views.py
from django.shortcuts import render

# Create your views here.

profiles/views.py
from django.contrib.auth.models import User
from django.views.generic import DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest
from feed.models import Post
from followers.models import Follower


class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    model = User
    template_name = "profile.html"
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    

    def get_context_data(self, **kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author=user).count()
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=user, followed_by=self.request.user).exists()
        return context

class FollowView(LoginRequiredMixin, View):
    http_method_names= ["post"]

    def post(self, request, *args, **kwargs):
        data=request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing Data")
        try:
            other_user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing User")
        if data['action'] == "follow":
            #Follow
            follower, created = Follower.objects.get_or_create(
                followed_by=request.user,
                following=other_user
            )
        else:
            #UnFollow
            try:
                follower = Follower.objects.get(
                    followed_by=request.user,
                    following=other_user,
                )
            except Follower.DoesNotExist:
                follower = None
            
            if follower:
                follower.delete()
        return JsonResponse({
            'success': True,
            'wording':"UnFollow" if data['action'] == "follow" else "Follow",
        })

feed/templates/feed/detail.html
{% extends 'base.html' %}

{% block body %}
{% include "includes/post.html" with post=post show_detail_link=False %}
{% endblock body %}

feed/templates/feed/homepage.html
{% extends 'base.html' %}


{% block body %}
<div class="grid 2xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-4" id="posts-container">

    {% for post in posts %}
    
        {% include "includes/post.html" with post=post show_detail_link=True %}
    
    {% endfor %}

</div>

{% endblock body %}

feed/templates/feed/new-post.html
{% extends 'base.html' %}


{% block title %}Create New Post{% endblock title %}


{% block body %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <div class="my-3">
        <button
            class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type="submit">
            <span class="mr-2">Add Post</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
            </svg>
        </button>
    </div>
</form>
{% endblock body %}

til/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Today I Learn!
        {% endblock title %}
    </title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
    
    {% block head %}
        
    {% endblock head %}
        
</head>

<body>
    <div class="min-h-screen flex flex-row bg-gray-100">
        <div class="flex flex-col w-56 bg-white rounded-r-3xl overflow-hidden">
            <div class="flex items-center justify-center h-20 shadow-md">
                <a href="/">
                    <h1 class="text-3xl uppercase text-indigo-500">TIL</h1>
                </a>
            </div>
            <ul class="flex flex-col py-4">
                <li>
                    <a href="/"
                        class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                        <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i
                                class="bx bx-home"></i></span>
                        <span class="text-sm font-medium">HOME</span>
                    </a>
                    {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url 'feed:new_post' %}"
                        class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800 js-toggle-modal">
                        <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i
                                class="bx bx-layer-plus"></i></span>
                        <span class="text-sm font-medium">ADD POST</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'account_logout' %}"
                        class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                        <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i
                                class="bx bx-log-out"></i></span>
                        <span class="text-sm font-medium">LOGOUT</span>
                    </a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'account_login' %}"
                        class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                        <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i
                                class="bx bx-log-in"></i></span>
                        <span class="text-sm font-medium">LOGIN</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="p-10 w-full">
            {% block body %}{% endblock body %}
        </div>


        <!-- component -->
        {% if request.user.is_authenticated %}
        <div
            class="flex items-center justify-center fixed left-0 bottom-0 w-full h-full bg-gray-800 bg-opacity-70 hidden js-modal">
            <div class="bg-white rounded-lg w-1/2">
                <div class="flex flex-col items-start p-4">
                    <div class="flex items-center w-full">
                        <div class="text-gray-900 font-medium text-lg">ADD NEW POST</div>
                        <svg class="ml-auto fill-current text-gray-700 w-6 h-6 cursor-pointer js-toggle-modal"
                            xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
                            <path
                                d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z" />
                        </svg>
                    </div>
                    <hr>
                    <div class="w-full">
                        <textarea class="border-2 border-blue-500 my-4 w-full js-post-text" placeholder="What's in your mind?" maxlength="240" rows="3" data-post-url="{% url 'feed:new_post' %}"></textarea>
                    </div>
                    <hr>
                    <div class="ml-auto">
                        <button
                            class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-3 inline-flex items-center js-submit"
                            type="button">
                            <span class="mr-2">Add Post</span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

til/templates/includes/post.html
{% load thumbnail %}

<div class="px-10 my-4 py-6 bg-white rounded-lg shadow-md">
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{post.date|date:"F j, Y, g:i:a"}}</span>
        <!-- <a class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500" href="#">Design</a> -->
    </div>
    <div class="mt-2">
        {% if show_detail_link %}
        <p class="mt-2 text-gray-600">{{post.text | truncatechars:50}}</p>
        {% else %}
        <p class="mt-2 text-gray-600">{{post.text}}</p>
        {% endif %}
    </div>
    <div class="flex justify-between items-center mt-4">
        
        {% if show_detail_link %}
        <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">Read more</a>
        {% else %}
        <span></span>
        {% endif %}
            
        
        <div>
            <a class="flex items-center" href="{% url 'profiles:detail' post.author.username %}">
                {% thumbnail post.author.profile.image "373x373" crop="center" as im %}
                <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="{{ im.url }}"
                    alt="avatar">
                {% endthumbnail %}
                <h1 class="text-gray-700 font-bold">{{ post.author.username }}</h1>
            </a>
        </div>
    </div>
</div>

til/templates/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{{user.username}}{% endblock title %}


{% block head %}
<style>
    .clip-bottom {
        clip-path: polygon(100% 50%, 0 0, 100% 0, 50% 100%, 0 0)
    }
</style>
{% endblock head %}

{% block body %}
<!-- component -->
<div class="rounded-3xl overflow-hidden shadow-xl max-w-xs my-3 bg-blue-500">
    <img src="https://i.imgur.com/dYcYQ7E.png" class="w-full" />
    <div class="relative flex justify-center -mt-8">
        {% if request.user.is_authenticated %}
        {% if request.user != user %}
        <button class="absolute top-4 right-10 cursor-pointer group js-follow" data-username="{{user.username}}" data-action="{% if you_follow %}un{% endif %}follow" data-url="{% url 'profiles:follow' user.username %}"
            type="button">
            <svg class="fill-green-400 hover:fill-green-600 js-svg-follow {% if you_follow %}hidden{% else %}{% endif %}" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                viewBox="0 0 24 24">
                <path
                    d="M18.5 2h-12C4.57 2 3 3.57 3 5.5V22l7-3.5 7 3.5v-9h5V5.5C22 3.57 20.43 2 18.5 2zM13 11h-2v2H9v-2H7V9h2V7h2v2h2v2zm7 0h-3V5.5c0-.827.673-1.5 1.5-1.5s1.5.673 1.5 1.5V11z">
                </path>
            </svg>
            <svg class="fill-green-400 hover:fill-green-600 js-svg-unfollow {% if you_follow %}{% else %}hidden{% endif %}" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24"><path d="M18.5 2h-12C4.57 2 3 3.57 3 5.5V22l7-3.5 7 3.5v-9h5V5.5C22 3.57 20.43 2 18.5 2zM13 11H7V9h6v2zm7 0h-3V5.5c0-.827.673-1.5 1.5-1.5s1.5.673 1.5 1.5V11z"></path></svg>
            <div
                class="[transform:perspective(50px)_translateZ(0)_rotateX(10deg)] group-hover:[transform:perspective(0px)_translateZ(0)_rotateX(0deg)] absolute bottom-0 mb-6 origin-bottom transform rounded text-white opacity-0 transition-all duration-300 group-hover:opacity-100">
                <div class="flex max-w-xs flex-col items-center">
                    <div class="rounded bg-gray-400 p-2 text-xs text-center shadow-lg js-follow-text">                        
                        {% if you_follow %}
                            UnFollow
                        {% else %}
                            Follow                            
                        {% endif %}
                    </div>
                    <div class="clip-bottom h-2 w-4 bg-gray-400"></div>
                </div>
            </div>
        </button>
        {% endif %}
        {% endif %}

        {% thumbnail user.profile.image "100x100" crop="center" as im %}
        <img src="{{ im.url }}" class="rounded-full border-solid border-white border-2 -mt-3">
        {% endthumbnail %}
    </div>
    <div class="text-center px-3 pb-6 pt-2">
        <h3 class="text-white text-sm bold font-sans">{{user.username}}</h3>
        <p class="mt-2 font-sans font-light text-white">Hello, i'm from another the other side!</p>
    </div>
    <div class="flex justify-center pb-3 text-white">
        <div class="text-center mr-3 border-r pr-3">
            <h2>{{ total_posts }}</h2>
            <span>Posts</span>
        </div>
        <div class="text-center">
            <h2>42</h2>
            <span>Followers</span>
        </div>
    </div>
</div>
{% endblock body %}